In [32]:
import pandas as pd

# Laden der Daten
file_path = 'Airbnb_Open_Data.csv'
airbnb_data = pd.read_csv(file_path)


airbnb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

/var/folders/qw/fl2h21817dv2w1mwt7hdh1th0000gn/T/ipykernel_3213/321840751.py:5: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb_data = pd.read_csv(file_path)

In [33]:
airbnb_data.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [34]:
airbnb_data.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [35]:
missing_values = airbnb_data.isnull().sum()
data_types = airbnb_data.dtypes

missing_values

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [36]:
data_types

id                                  int64
NAME                               object
host id                             int64
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
country                            object
country code                       object
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
house_rules                        object
license                            object
dtype: object

In [37]:
row = airbnb_data.loc[airbnb_data['reviews per month']==False]

row

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license]
Index: []

In [38]:
cleaned_data = airbnb_data.copy()

# Fehlende Werte in 'license' durch 'no' ersetzen
cleaned_data['license'] = cleaned_data['license'].fillna('no',)

# Fehlende Werte in 'house_rules' durch 'no' ersetzen
cleaned_data['house_rules']  = cleaned_data['house_rules'].fillna('no')

# Überprüfen der Änderungen
missing_values_step_1 = cleaned_data[['license', 'house_rules']].isnull().sum()
missing_values_step_1

license        0
house_rules    0
dtype: int64

In [39]:
# Fehlende Werte in 'last review' durch 'missing' ersetzen
cleaned_data['last review'] = cleaned_data['last review'].fillna('missing')

# Überprüfen der Änderungen
missing_values_step_2 = cleaned_data['last review'].isnull().sum()
missing_values_step_2

np.int64(0)

In [40]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_reviews_per_month(row):
    if pd.isnull(row['reviews per month']):
        if row['number of reviews'] > 0:
            median_value = cleaned_data[cleaned_data['neighbourhood group'] == row['neighbourhood group']]['reviews per month'].median()
            if pd.isna(median_value):
                median_value = cleaned_data[cleaned_data['neighbourhood'] == row['neighbourhood']]['reviews per month'].median()
            return median_value
        else:
            return 0
    return row['reviews per month']

# Fehlende Werte in 'reviews per month' ersetzen
cleaned_data['reviews per month'] = cleaned_data.apply(fill_reviews_per_month, axis=1)

# Überprüfen der Änderungen
missing_values_step_3 = cleaned_data['reviews per month'].isnull().sum()
cleaned_data[cleaned_data['reviews per month'].isnull()]

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license]
Index: []

In [41]:
# Entfernen von Einträgen mit fehlenden Werten in 'lat' oder 'long'
cleaned_data = cleaned_data.dropna(subset=['lat', 'long'])

# Überprüfen der Änderungen
missing_values_after_dropping = cleaned_data[['lat', 'long']].isnull().sum()
missing_values_after_dropping

lat     0
long    0
dtype: int64

In [42]:
# Fehlende Werte in 'host name' durch 'anonymous' ersetzen
cleaned_data['host name'] = cleaned_data['host name'].fillna('anonymous')

# Überprüfen der Änderungen
missing_values_step_4 = cleaned_data['host name'].isnull().sum()
missing_values_step_4

np.int64(0)

In [43]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

# Konvertiere Längen- und Breitengrade in Radianten
cleaned_data['lat_rad'] = np.radians(cleaned_data['lat'])
cleaned_data['long_rad'] = np.radians(cleaned_data['long'])

# BallTree für effiziente Nachbarschaftssuche erstellen
coords = cleaned_data[['lat_rad', 'long_rad']].values
tree = BallTree(coords, metric='haversine')

# Funktion zum Finden der häufigsten 'neighbourhood group' innerhalb eines Radius von 5 km
def fill_neighbourhood_group(row):
    if pd.isnull(row['neighbourhood group']):
        lat, long = row['lat'], row['long']
        coord_rad = np.radians([lat, long])
        # Suche Nachbarn innerhalb von 5 km (0.005 ist der ungefähre Radius in Radianten)
        indices = tree.query_radius([coord_rad], r=5 / 6371.0)[0]
        nearby = cleaned_data.iloc[indices]
        if not nearby.empty:
            return nearby['neighbourhood group'].mode()[0]
    return row['neighbourhood group']

# Fehlende Werte in 'neighbourhood group' ersetzen
cleaned_data['neighbourhood group'] = cleaned_data.apply(fill_neighbourhood_group, axis=1)

# Überprüfen der Änderungen
missing_values_step_9 = cleaned_data['neighbourhood group'].isnull().sum()
missing_values_step_9

np.int64(0)

In [44]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_minimum_nights(row):
    if pd.isnull(row['minimum nights']):
        median_value = cleaned_data[cleaned_data['neighbourhood group'] == row['neighbourhood group']]['minimum nights'].median()
        return median_value
    return row['minimum nights']

# Fehlende Werte in 'minimum nights' ersetzen
cleaned_data['minimum nights'] = cleaned_data.apply(fill_minimum_nights, axis=1)

# Überprüfen der Änderungen
missing_values_step_5 = cleaned_data['minimum nights'].isnull().sum()
missing_values_step_5

np.int64(0)

In [45]:
# Fehlende Werte in 'calculated host listings count' durch 1 ersetzen, wenn 'host_identity_verified' nicht NaN ist, ansonsten Eintrag entfernen
cleaned_data['calculated host listings count'] = cleaned_data.apply(
    lambda row: 1 if pd.isnull(row['calculated host listings count']) and pd.notnull(row['host_identity_verified']) else row['calculated host listings count'], axis=1
)
cleaned_data = cleaned_data[cleaned_data['calculated host listings count'].notnull()]

# Überprüfen der Änderungen
missing_values_step_6 = cleaned_data['calculated host listings count'].isnull().sum()
missing_values_step_6

np.int64(0)

In [46]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_availability_365(row):
    if pd.isnull(row['availability 365']):
        median_value = cleaned_data[cleaned_data['neighbourhood group'] == row['neighbourhood group']]['availability 365'].median()
        return median_value
    return row['availability 365']

# Fehlende Werte in 'availability 365' ersetzen
cleaned_data['availability 365'] = cleaned_data.apply(fill_availability_365, axis=1)

# Überprüfen der Änderungen
missing_values_step_7 = cleaned_data['availability 365'].isnull().sum()
missing_values_step_7

np.int64(0)

In [47]:
# Fehlende Werte in 'host_identity_verified' durch 'verified' ersetzen, wenn 'number of reviews' > 9, ansonsten 'unconfirmed'
cleaned_data['host_identity_verified'] = cleaned_data.apply(
    lambda row: 'verified' if pd.isnull(row['host_identity_verified']) and row['number of reviews'] > 9 else 'unconfirmed' if pd.isnull(row['host_identity_verified']) else row['host_identity_verified'],
    axis=1
)

# Überprüfen der Änderungen
missing_values_step_8 = cleaned_data['host_identity_verified'].isnull().sum()
missing_values_step_8

np.int64(0)

In [48]:
# from geopy.distance import geodesic

# # Funktion zum Finden der häufigsten 'neighbourhood group' innerhalb eines Radius von 5 km
# def fill_neighbourhood_group(row):
#     if pd.isnull(row['neighbourhood group']):
#         lat, long = row['lat'], row['long']
#         distances = cleaned_data.apply(lambda x: geodesic((lat, long), (x['lat'], x['long'])).km, axis=1)
#         nearby = cleaned_data[distances <= 5]
#         if not nearby.empty:
#             return nearby['neighbourhood group'].mode()[0]
#     return row['neighbourhood group']

# # Fehlende Werte in 'neighbourhood group' ersetzen
# cleaned_data['neighbourhood group'] = cleaned_data.apply(fill_neighbourhood_group, axis=1)

# # Überprüfen der Änderungen
# missing_values_step_9 = cleaned_data['neighbourhood group'].isnull().sum()
# missing_values_step_9

In [49]:
cleaned_data['country'] = cleaned_data['country'].fillna('United States',)
cleaned_data['NAME'] = cleaned_data['NAME'].fillna('missing',)
cleaned_data['country code'] = cleaned_data['country code'].fillna('US',)
cleaned_data['instant_bookable'] = cleaned_data['instant_bookable'].fillna('false',)
cleaned_data['cancellation_policy'] = cleaned_data['cancellation_policy'].fillna('unknown',)

In [50]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_review_rate_number(row):
    if pd.isnull(row['review rate number']):
        median_value = cleaned_data[cleaned_data['neighbourhood group'] == row['neighbourhood group']]['review rate number'].median()
        return median_value
    return row['review rate number']

# Fehlende Werte in 'minimum nights' ersetzen
cleaned_data['review rate number'] = cleaned_data.apply(fill_minimum_nights, axis=1)

# Überprüfen der Änderungen
missing_values_step_5 = cleaned_data['review rate number'].isnull().sum()
missing_values_step_5

np.int64(0)

In [51]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_service_fee(row):
    if pd.isnull(row['service fee']):
        median_value = cleaned_data[cleaned_data['neighbourhood group'] == row['neighbourhood group']]['service fee'].median()
        return median_value
    return row['service fee']

# Fehlende Werte in 'minimum nights' ersetzen
cleaned_data['service fee'] = cleaned_data.apply(fill_minimum_nights, axis=1)

# Überprüfen der Änderungen
missing_values_step_5 = cleaned_data['service fee'].isnull().sum()
missing_values_step_5

np.int64(0)

In [52]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_price(row):
    if pd.isnull(row['price']):
        median_value = cleaned_data[cleaned_data['neighbourhood group'] == row['neighbourhood group'] and cleaned_data['room type'] == row['room type']]['price'].median()
        return median_value
    return row['price']

# Fehlende Werte in 'minimum nights' ersetzen
cleaned_data['price'] = cleaned_data.apply(fill_minimum_nights, axis=1)

# Überprüfen der Änderungen
missing_values_step_5 = cleaned_data['price'].isnull().sum()
missing_values_step_5

np.int64(0)

In [53]:
# Funktion zum Berechnen des Medians in der gleichen 'neighbourhood group'
def fill_constuction_year(row):
    if pd.isnull(row['Construction year']):
        median_value = cleaned_data[cleaned_data['neighbourhood'] == row['neighbourhood']]['Construction year'].median()
        return median_value
    return row['Construction year']

# Fehlende Werte in 'minimum nights' ersetzen
cleaned_data['Construction year'] = cleaned_data.apply(fill_minimum_nights, axis=1)

# Überprüfen der Änderungen
missing_values_step_5 = cleaned_data['Construction year'].isnull().sum()
missing_values_step_5

np.int64(0)

In [54]:
# Fehlende Werte in 'calculated host listings count' durch 1 ersetzen, wenn 'host_identity_verified' nicht NaN ist, ansonsten Eintrag entfernen
cleaned_data['number of reviews'] = cleaned_data.apply(
    lambda row: 1 if pd.isnull(row['number of reviews']) and pd.notnull(row['review rate number']) else row['number of reviews'], axis=1
)
cleaned_data = cleaned_data[cleaned_data['calculated host listings count'].notnull()]

# Überprüfen der Änderungen
missing_values_step_6 = cleaned_data['calculated host listings count'].isnull().sum()
missing_values_step_6

np.int64(0)

In [55]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

# Konvertiere Längen- und Breitengrade in Radianten
cleaned_data['lat_rad'] = np.radians(cleaned_data['lat'])
cleaned_data['long_rad'] = np.radians(cleaned_data['long'])

# BallTree für effiziente Nachbarschaftssuche erstellen
coords = cleaned_data[['lat_rad', 'long_rad']].values
tree = BallTree(coords, metric='haversine')

# Funktion zum Finden der häufigsten 'neighbourhood group' innerhalb eines Radius von 5 km
def fill_neighbourhood(row):
    if pd.isnull(row['neighbourhood']):
        lat, long = row['lat'], row['long']
        coord_rad = np.radians([lat, long])
        # Suche Nachbarn innerhalb von 5 km (0.005 ist der ungefähre Radius in Radianten)
        indices = tree.query_radius([coord_rad], r=5 / 6371.0)[0]
        nearby = cleaned_data.iloc[indices]
        if not nearby.empty:
            return nearby['neighbourhood'].mode()[0]
    return row['neighbourhood']

# Fehlende Werte in 'neighbourhood group' ersetzen
cleaned_data['neighbourhood'] = cleaned_data.apply(fill_neighbourhood_group, axis=1)

# Überprüfen der Änderungen
missing_values_step_9 = cleaned_data['neighbourhood'].isnull().sum()
missing_values_step_9

np.int64(0)

In [56]:
# Berechnen der fehlenden Werte und Datentypen
missing_values = cleaned_data.isnull().sum()
data_types = cleaned_data.dtypes

# Fehlende Werte absteigend sortieren
missing_values_sorted = missing_values.sort_values(ascending=False)

# Anzeige der sortierten fehlenden Werte
missing_values_sorted

id                                0
NAME                              0
lat_rad                           0
license                           0
house_rules                       0
availability 365                  0
calculated host listings count    0
review rate number                0
reviews per month                 0
last review                       0
number of reviews                 0
minimum nights                    0
service fee                       0
price                             0
Construction year                 0
room type                         0
cancellation_policy               0
instant_bookable                  0
country code                      0
country                           0
long                              0
lat                               0
neighbourhood                     0
neighbourhood group               0
host name                         0
host_identity_verified            0
host id                           0
long_rad                          0
dtype: int64

In [57]:
pd.set_option('display.max_columns', None)
cleaned_data.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,lat_rad,long_rad
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Brooklyn,40.64749,-73.97237,United States,US,False,strict,Private room,10.0,10.0,10.0,10.0,9.0,10/19/2021,0.21,10.0,6.0,286.0,Clean up and treat the home the way you'd like...,no,0.709433,-1.291061
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Manhattan,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,30.0,30.0,30.0,30.0,45.0,5/21/2022,0.38,30.0,2.0,228.0,Pet friendly but please confirm with me if the...,no,0.711285,-1.291260
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,unconfirmed,Elise,Manhattan,Manhattan,40.80902,-73.94190,United States,US,True,flexible,Private room,3.0,3.0,3.0,3.0,0.0,missing,0.00,3.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",no,0.712252,-1.290530
3,1002755,missing,85098326012,unconfirmed,Garry,Brooklyn,Brooklyn,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,30.0,30.0,30.0,30.0,270.0,7/5/2019,4.64,30.0,1.0,322.0,no,no,0.710090,-1.290841
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,Manhattan,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,10.0,10.0,10.0,10.0,9.0,11/19/2018,0.10,10.0,1.0,289.0,"Please no smoking in the house, porch or on th...",no,0.712068,-1.290566

In [58]:
cleaned_data[cleaned_data['price'].isna()]

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license, lat_rad, long_rad]
Index: []

In [59]:
cleaned_data.describe()

,id,host id,lat,long,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,lat_rad,long_rad
count,1.025820e+05,1.025820e+05,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000,102582.000000
mean,2.915086e+07,4.925544e+10,40.728093,-73.949642,8.115166,8.115166,8.115166,8.115166,27.427677,1.161590,8.115166,7.916174,140.957371,0.710839,-1.290665
std,1.625489e+07,2.853933e+10,0.055857,0.049523,30.497052,30.497052,30.497052,30.497052,49.456708,1.680934,30.497052,32.173516,135.176207,0.000975,0.000864
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,-1223.000000,-1223.000000,-1223.000000,-1223.000000,0.000000,0.000000,-1223.000000,1.000000,-10.000000,0.706855,-1.295904
25%,1.509286e+07,2.458340e+10,40.688740,-73.982580,2.000000,2.000000,2.000000,2.000000,1.000000,0.090000,2.000000,1.000000,3.000000,0.710152,-1.291240
50%,2.914130e+07,4.911887e+10,40.722290,-73.954440,3.000000,3.000000,3.000000,3.000000,7.000000,0.480000,3.000000,1.000000,97.000000,0.710738,-1.290748
75%,4.320355e+07,7.399747e+10,40.762760,-73.932350,5.000000,5.000000,5.000000,5.000000,30.000000,1.710000,5.000000,2.000000,268.000000,0.711444,-1.290363
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,5645.000000,5645.000000,5645.000000,5645.000000,1024.000000,90.000000,5645.000000,332.000000,3677.000000,0.714136,-1.286399

In [60]:

# Überprüfen auf unplausible Werte in den angegebenen Spalten

# Construction year: Negative Werte oder Werte größer als 2024
invalid_construction_year_before = cleaned_data[(cleaned_data['Construction year'] < 0) | (cleaned_data['Construction year'] > 2024)].shape[0]

# Price: keine negativen Werte
# Zuerst sicherstellen, dass die Spalte price numerisch ist
cleaned_data['price'] = pd.to_numeric(cleaned_data['price'], errors='coerce')
invalid_price_before = cleaned_data[(cleaned_data['price'] < 0)].shape[0]

# Entfernen der unplausiblen Einträge
cleaned_data = cleaned_data[(cleaned_data['Construction year'] >= 0) & (cleaned_data['Construction year'] <= 2024)]
cleaned_data = cleaned_data[cleaned_data['price'] >= 0]

# Überprüfen, ob die unplausiblen Werte entfernt wurden
invalid_construction_year_after = cleaned_data[(cleaned_data['Construction year'] < 0) | (cleaned_data['Construction year'] > 2024)].shape[0]
invalid_price_after = cleaned_data[(cleaned_data['price'] < 0)].shape[0]

# Ergebnisse anzeigen
invalid_entries_before = {
    'Invalid Construction Year Before': invalid_construction_year_before,
    'Invalid Price Before': invalid_price_before,
}

invalid_entries_after = {
    'Invalid Construction Year After': invalid_construction_year_after,
    'Invalid Price After': invalid_price_after,
}

print("Anzahl unplausibler Einträge vor der Bereinigung:")
print(invalid_entries_before)

print("Anzahl unplausibler Einträge nach der Bereinigung:")
print(invalid_entries_after)

Anzahl unplausibler Einträge vor der Bereinigung:
{'Invalid Construction Year Before': 16, 'Invalid Price Before': 13}
Anzahl unplausibler Einträge nach der Bereinigung:
{'Invalid Construction Year After': 0, 'Invalid Price After': 0}

In [61]:
# Überprüfen auf negative Werte in numerischen Spalten, aber ohne die Spalte 'long'
numerical_columns = cleaned_data.select_dtypes(include=['float64', 'int64']).columns
numerical_columns = numerical_columns.drop('long')  # Spalte 'long' ausschließen
numerical_columns = numerical_columns.drop('long_rad')  # Spalte 'long' ausschließen

negative_values = cleaned_data[(cleaned_data[numerical_columns] < 0).any(axis=1)]

print("Einträge mit negativen Werten in numerischen Spalten (ohne 'long'):")
print(negative_values)

# Überprüfen auf Tippfehler in string-basierten Spalten
string_columns = cleaned_data.select_dtypes(include=['object']).columns

# Funktion zur Überprüfung auf mögliche Tippfehler
def find_possible_typos(column):
    value_counts = column.value_counts()
    possible_typos = value_counts[value_counts <= 5]  # Annahme: Werte mit sehr wenigen Vorkommen könnten Tippfehler sein
    return possible_typos

# Überprüfung der string-basierten Spalten auf mögliche Tippfehler
for col in string_columns:
    typos = find_possible_typos(cleaned_data[col])
    if not typos.empty:
        print(f"Mögliche Tippfehler in der Spalte '{col}':")
        print(typos)

# Beispielhafte Anzeige der Ergebnisse
print(cleaned_data.head())

Einträge mit negativen Werten in numerischen Spalten (ohne 'long'):
              id                                               NAME  \
139      1078106                                    FLAT MACDONOUGH
142      1079763        Sun-drenched, artsy modernist 1 BDRM duplex
170      1095227                          New York room with a view
236      1131679                                            missing
251      1139963                        B NYC Staten Alternative...
...          ...                                                ...
86735   48905077     Comfortable 2 BR in East Village/Cooper Square
86764   48921093  Beautiful hip location, with a light of sunshine.
86790   48935453          Beautiful Quiet Bedroom near City College
86853   48970248   West Chelsea 1 bedroom 2 bathroom outdoor space.
102559   6073107                      Beautiful Brooklyn Brownstone

            host id host_identity_verified  host name neighbourhood group  \
139     12359551036            unconfirmed  Frederick            Brooklyn
142     83716006050            unconfirmed     Kellan            Brooklyn
170     95792367490               verified     Dexter       Staten Island
236     74291995690            unconfirmed    Cameron           Manhattan
251     13992927619               verified     Fowler       Staten Island
...             ...                    ...        ...                 ...
86735   66319244844            unconfirmed     Cooper           Manhattan
86764   11182626298               verified      Noemi              Queens
86790   59344299465            unconfirmed      Erika           Manhattan
86853   34380933090            unconfirmed     Alison           Manhattan
102559  68582965292               verified      Megan            Brooklyn

        neighbourhood       lat      long        country country code  \
139          Brooklyn  40.68296 -73.93662  United States           US
142          Brooklyn  40.71561 -73.94835  United States           US
170     Staten Island  40.64524 -74.08088  United States           US
236         Manhattan  40.79163 -73.94573  United States           US
251     Staten Island  40.63627 -74.08543  United States           US
...               ...       ...       ...            ...          ...
86735       Manhattan  40.72627 -73.99145  United States           US
86764          Queens  40.70971 -73.89741  United States           US
86790       Manhattan  40.81863 -73.95295  United States           US
86853       Manhattan  40.74584 -74.00279  United States           US
102559       Brooklyn  40.68110 -73.95275  United States           US

       instant_bookable cancellation_policy        room type  \
139               False            flexible  Entire home/apt
142                True            moderate  Entire home/apt
170                True              strict     Private room
236               False            flexible  Entire home/apt
251                True              strict     Private room
...                 ...                 ...              ...
86735              True            moderate  Entire home/apt
86764             False            flexible  Entire home/apt
86790             False              strict     Private room
86853              True            flexible  Entire home/apt
102559             True            moderate     Private room

        Construction year  price  service fee  minimum nights  \
139                   3.0    3.0          3.0             3.0
142                   3.0    3.0          3.0             3.0
170                 131.0  131.0        131.0           131.0
236                  28.0   28.0         28.0            28.0
251                   2.0    2.0          2.0             2.0
...                   ...    ...          ...             ...
86735                 3.0    3.0          3.0             3.0
86764                28.0   28.0         28.0            28.0
86790                 2.0    2.0          2.0             2.0
86853                14.0   14.0         14.0            14.0
102559                1.0    1.0          1.0             1.0

        number of reviews last review  reviews per month  review rate number  \
139                 227.0   6/23/2019               2.09                 3.0
142                  10.0     missing               0.10                 3.0
170                 166.0   6/13/2019               1.66               131.0
236                 183.0   9/29/2018               1.83                28.0
251                 147.0     missing               1.20                 2.0
...                   ...         ...                ...                 ...
86735                27.0   4/23/2019               0.76                 3.0
86764                 1.0   9/15/2018               0.10                28.0
86790                 0.0     missing               0.00                 2.0
86853                 0.0     missing               0.00                14.0
102559                0.0     missing               0.00                 1.0

        calculated host listings count  availability 365  \
139                                2.0             -10.0
142                                1.0              -2.0
170                                1.0              -1.0
236                                2.0              -6.0
251                                6.0              -1.0
...                                ...               ...
86735                              1.0              -4.0
86764                              1.0              -2.0
86790                              3.0              -7.0
86853                              1.0              -7.0
102559                             1.0              -6.0

                                              house_rules license   lat_rad  \
139                                                    no      no  0.710052
142             Quiet after 11pm.  Other guests sleeping.      no  0.710621
170     Please tell me about who you will be traveling...      no  0.709393
236     - We have school age children and request that...      no  0.711948
251     Rules are detailed in the House Manual, which ...      no  0.709237
...                                                   ...     ...       ...
86735   No Smoking in the Apartment.  Pretty laid back...      no  0.710808
86764                                                  no      no  0.710518
86790   Please be respectful of other guests.  Keep th...      no  0.712419
86853   - $20 per extra person. Maximum 2 person for a...      no  0.711149
102559  Use of all of kitchen except gas stove/oven. T...      no  0.710019

        long_rad
139    -1.290437
142    -1.290642
170    -1.292955
236    -1.290596
251    -1.293035
...          ...
86735  -1.291394
86764  -1.289753
86790  -1.290722
86853  -1.291592
102559 -1.290719

[432 rows x 28 columns]
Mögliche Tippfehler in der Spalte 'NAME':
NAME
Park Slope Gem                                        5
Lovely room                                           5
Gorgeous Room with Private Bathroom in Manhattan      5
Brownstone Studio                                     5
Private bedroom in East Village                       5
                                                     ..
Rare and spacious apartment. 15 mins to Manhattan.    1
The Perfect Room 1 stop to East Village!              1
Weekend Getaway                                       1
MANHATTAN CLUB - 1 BEDROOM SUITE                      1
Parisian Style Apartment in Heart of Brooklyn         1
Name: count, Length: 61099, dtype: int64
Mögliche Tippfehler in der Spalte 'host name':
host name
Pasha                5
Aurelio              5
Viktoriya            5
Milica               5
Sigal                5
                    ..
Tanmaya              1
Stratos              1
Shannan              1
Samuel & Toluwani    1
Nadia Dara           1
Name: count, Length: 10358, dtype: int64
Mögliche Tippfehler in der Spalte 'neighbourhood group':
neighbourhood group
brookln     1
manhatan    1
Name: count, dtype: int64
Mögliche Tippfehler in der Spalte 'neighbourhood':
neighbourhood
brookln     1
manhatan    1
Name: count, dtype: int64
Mögliche Tippfehler in der Spalte 'last review':
last review
4/11/2021     5
5/5/2021      5
7/15/2020     5
7/17/2020     5
10/12/2014    5
             ..
4/24/2015     1
2/17/2015     1
2/10/2016     1
4/22/2015     1
2/3/2016      1
Name: count, Length: 840, dtype: int64
Mögliche Tippfehler in der Spalte 'house_rules':
house_rules
- 1.Guest(s) agree to NO PARTIES anywhere on the property. Legal action will be taken for parties that cause damages to the unit, property, reputation, or relationship with building staff or other residents.  2.Smoking of any kind is not permitted in the unit or on the premises. Fee for smoking will be 10 times your total reservation cost. For example, your total reservation cost is $350. Fee for smoking on premises will be $3,500. 3.Guests agree to abide by maximum occupancy of unit, and observe quiet hours between 9pm and 9am  4.Guests are responsible for action of ALL GUESTS occupying their unit at all times.  5.Guests agree to return all keys, remotes. Replacement fees may apply for unreturned items  6.Guests understand that onsite building staff (maintenance and concierge) are not affiliated with AIRBNB. Please contact me directly for any needed items.  7.Guests understand that no pets are to be in the unit.  8.Guests agree to pay replacement cost for any unreturned items, and $18    5
- 1.Guest(s) agree to NO PARTIES anywhere on the property. Legal action will be taken for parties that cause damages to the unit, property, reputation, or relationship with building staff or other residents.  2.Smoking of any kind is not permitted in the unit or on the premises. Fee for smoking will be 10 times your total reservation cost. For example, your total reservation cost is $350. Fee for smoking on premises will be $3,500. 3.Guests agree to abide by maximum occupancy of unit, and observe quiet hours between 9pm and 9am  4.Guests are responsible for action of ALL GUESTS occupying their unit at all times.  5.Guests agree to return all keys, remotes. Replacement fees may apply for unreturned items  6.Guests understand that onsite building staff (maintenance and concierge) are not affiliated with AIRBNB. Please contact me directly for any needed items.  7.Guests understand that no pets are to be in the unit.  8.Guests agree to pay replacement cost for any unreturned items, and $16    4
- 1.Guest(s) agree to NO PARTIES anywhere on the property. Legal action will be taken for parties that cause damages to the unit, property, reputation, or relationship with building staff or other residents.  2.Smoking of any kind is not permitted in the unit or on the premises. Fee for smoking will be 10 times your total reservation cost. For example, your total reservation cost is $350. Fee for smoking on premises will be $3,500. 3.Guests agree to abide by maximum occupancy of unit, and observe quiet hours between 9pm and 9am  4.Guests are responsible for action of ALL GUESTS occupying their unit at all times.  5.Guests agree to return all keys, remotes. Replacement fees may apply for unreturned items  6.Guests understand that onsite building staff (maintenance and concierge) are not affiliated with AIRBNB. Please contact me directly for any needed items.  7.Guests understand that no pets are to be in the unit.  8.Guests agree to pay replacement cost for any unreturned items, and $21    4
- 1.Guest(s) agree to NO PARTIES anywhere on the property. Legal action will be taken for parties that cause damages to the unit, property, reputation, or relationship with building staff or other residents.  2.Smoking of any kind is not permitted in the unit or on the premises. Fee for smoking will be 10 times your total reservation cost. For example, your total reservation cost is $350. Fee for smoking on premises will be $3,500. 3.Guests agree to abide by maximum occupancy of unit, and observe quiet hours between 9pm and 9am  4.Guests are responsible for action of ALL GUESTS occupying their unit at all times.  5.Guests agree to return all keys, remotes. Replacement fees may apply for unreturned items  6.Guests understand that onsite building staff (maintenance and concierge) are not affiliated with AIRBNB. Please contact me directly for any needed items.  7.Guests understand that no pets are to be in the unit.  8.Guests agree to pay replacement cost for any unreturned items, and $20    4
No smoking anywhere in or out of home (guest must be non-smoker) Cologne/perfume/spray use are not allowed any time anywhere (allergy prevent) Please be aware of your actions and always look back before leaving bathroom to make sure everything is left clean Please cause no disturbance and walk the stairs slower to prevent much noise OK to eat in your room but not in bed, always clean/cover food Keep your room clean during your stay Recycle and use reusable shopping bag (provided, please carry with you) Please do not bring plastic bags from stores Ask for help/assistance/information at any time, we want you to feel comfortable Night time help please call from the same phone number twice or more if the call is not answered Do not give mailing address to anyone (ask me why) If guest breaks rule about mailing address, the charge is $205                                                                                                                                                                4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
No smoking anywhere in or out of home (guest must be non-smoker) Cologne/perfume/spray use are not allowed any time anywhere (allergy prevent) Please be aware of your actions and always look back before leaving bathroom to make sure everything is left clean Please cause no disturbance and walk the stairs slower to prevent much noise OK to eat in your room but not in bed, always clean/cover food Keep your room clean during your stay Recycle and use reusable shopping bag (provided, please carry with you) Please do not bring plastic bags from stores Ask for help/assistance/information at any time, we want you to feel comfortable Night time help please call from the same phone number twice or more if the call is not answered Do not give mailing address to anyone (ask me why) If guest breaks rule about mailing address, the charge is $202                                                                                                                                                                1
5 nights minimum stay, no smoking or pets.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
4 nights minimum stay No pets at any time No smoking Please be mindful of the furniture and personal belongings, it was all furnished with designer pieces and hard to replace things.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
4 guest maximum.  Smoking isn't permitted and unfortunately neither are pets. Sorry.   Quiet hours 9p-8a.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
16 nights minimum stay, no smoking or pets.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Name: count, Length: 153, dtype: int64
Mögliche Tippfehler in der Spalte 'license':
license
41662/AL    2
Name: count, dtype: int64
        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823

In [62]:
# Mapping von Tippfehlern zu den richtigen Werten
correction_mapping = {
    'brookln': 'Brooklyn',
    'manhatan': 'Manhattan'
}

# Tippfehler in 'neighbourhood group' korrigieren
cleaned_data['neighbourhood group'] = cleaned_data['neighbourhood group'].replace(correction_mapping)

# Tippfehler in 'neighbourhood' korrigieren
cleaned_data['neighbourhood'] = cleaned_data['neighbourhood'].replace(correction_mapping)

# Überprüfen der Änderungen
print("Einzigartige Werte in 'neighbourhood group':")
print(cleaned_data['neighbourhood group'].unique())

print("\nEinzigartige Werte in 'neighbourhood':")
print(cleaned_data['neighbourhood'].unique())

# Speichern der bereinigten Daten
cleaned_data.to_csv('Airbnb_Open_Data_Cleaned.csv', index=False)

Einzigartige Werte in 'neighbourhood group':
['Brooklyn' 'Manhattan' 'Queens' 'Staten Island' 'Bronx']

Einzigartige Werte in 'neighbourhood':
['Brooklyn' 'Manhattan' 'Queens' 'Staten Island' 'Bronx']